name: 'Rewritable Pull Request / Issue Comment'
branding:
  icon: 'message-circle'  
  color: 'red'
description: 'Posts a PR / issue comment that re-writes itself on an update'
inputs: 
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
  COMMENT_IDENTIFIER:
    description: 'A unique identifier for the re-writable comment (can be the purpose of the comment)'
  ISSUE_ID:
    description: 'The identifier for a PR / issue that the comment should be made on. Defaults to the PR that the workflow is running on'
  message:
    description: 'Message that should be printed in the pull request'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
outputs:
  comment-id:
    description: 'The ID of the newly created / updated comment'
