#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: "Detect Secrets"

# https://github.com/Yelp/detect-secrets

on:
  pull_request:
    branches:
      - main
      - master
      - "!repo-sync/**"
      - "!renovate/**"
      - "!update/pre-commit-hooks/**"
  workflow_dispatch:

jobs:
  detect-secrets:
    name: "Detect Secrets in Code"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: run detect-secrets
        uses: reviewdog/action-detect-secrets@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: "true"
          level: warning
          detect_secrets_flags: "--all-files --force-use-all-plugins"
          # filter_mode: "nofilter" # Optional. Check all files, not just the diff
#
# Allowlisting Secrets
#
# It is possible to disable detection for individual lines of code in case of false positives.
# To do this, add a comment at the end of the line with text `pragma: allowlist secret`
#
# public_key: |  # pragma: allowlist secret
#    gX69YO4CvBsVjzAwYxdG
#    yDd30t5+9ez31gKATtj4
#
# Or add a comment with the text `pragma: allowlist nextline secret` before the line.
# pragma: allowlist nextline secret
# public_key = gX69YO4CvBsVjzAwYxdG
